config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :matches

  resources :teams

  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'teams#index'
  

  
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team
  belongs_to :away_team



  before_save :date_wontbe_past
  

  private

  def date_wontbe_past
    if date && date < Date.today
      errors[:date] = "Cannot be in the past"
      throw(:abort)
    end
  end

 


  scope :upcoming, -> { where("date >= ?", Date.today) }
  scope :for_team, ->(team_id) { where("home_team_id = ? OR away_team_id = ?", team_id, team_id) }
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy!

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:location, :date, :home_team_id, :away_team_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :home_team_id, style: "display: block" %>
    <%= form.text_field :home_team_id %>
  </div>

  <div>
    <%= form.label :away_team_id, style: "display: block" %>
    <%= form.text_field :away_team_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>Location:</strong>
    <%= match.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= match.date %>
  </p>

  <p>
    <strong>Home team:</strong>
    <%= match.home_team_id %>
  </p>

  <p>
    <strong>Away team:</strong>
    <%= match.away_team_id %>
  </p>

</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches</h1>

<div id="matches">
  <% @matches.each do |match| %>
    <%= render match %>
    <p>
      <%= link_to "Show this match", match %>
    </p>
  <% end %>
</div>

<%= link_to "New match", new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>